### ISSUE TITLE
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by bala-v** [icedevil2001/mark_minervini_stock_screener#1]
Getting the error when running app and UI simply says `running` 

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/stock-screener/lib/python3.8/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/stock-screener/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Caskroom/miniconda/base/envs/stock-screener/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Caskroom/miniconda/base/envs/stock-screener/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/stock-screener/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/Caskroom/miniconda/base/envs/stock-screener/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/stock-screener/lib/python3.8/site-packages/multitasking/__init__.py", line 104, in _run_via_pool
    return callee(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/stock-screener/lib/python3.8/site-packages/yfinance/multi.py", line 166, in _download_one_threaded
    data = _download_one(ticker, start, end, auto_adjust, back_adjust,
  File "/usr/local/Caskroom/miniconda/base/envs/stock-screener/lib/python3.8/site-packages/yfinance/multi.py", line 178, in _download_one
    return Ticker(ticker).history(period=period, interval=interval,
  File "/usr/local/Caskroom/miniconda/base/envs/stock-screener/lib/python3.8/site-packages/yfinance/base.py", line 156, in history
    data = data.json()
  File "/usr/local/Caskroom/miniconda/base/envs/stock-screener/lib/python3.8/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by icedevil2001** [comment]
Thank you for your feedback. The issue is likely related to the `yfinance` API. I will be updating my code in the coming weeks. Please keep an eye out for updates.

**Comment by bala-v** [comment]
Thanks @icedevil2001 Looking forward to it. If there are other interesting repo's for learning quant would much appreciate the pointers!.
